repos:
- repo: https://github.com/executablebooks/mdformat
  rev: 08fba30538869a440b5059de90af03e3502e35fb  # frozen: 0.7.17
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-gfm
- repo: https://github.com/asottile/yesqa
  rev: f2ae90cf9e1661ade79d0881186ce4fd7ba6ee79  # frozen: v1.5.0
  hooks:
  - id: yesqa
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/PyCQA/isort
  rev: c235f5e450b4b84e58d114ed4c589cbf454175a3  # frozen: 5.13.2
  hooks:
  - id: isort
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: c53240a7f974b3707e13eac6710542cc96a2d61a  # frozen: 24.10.0
  hooks:
  - id: black
- repo: https://github.com/hukkin/docformatter
  rev: ab802050e6e96aaaf7f917fcbc333bb74e2e57f7  # frozen: v1.4.2
  hooks:
  - id: docformatter
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
  hooks:
  - id: check-yaml
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316  # frozen: v1.10.0
  hooks:
  - id: python-use-type-annotations
  - id: python-check-blanket-noqa
  - id: python-check-blanket-type-ignore
- repo: https://github.com/PyCQA/flake8
  rev: e43806be3607110919eff72939fda031776e885a  # frozen: 7.1.1
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: d4911cfb7f1010759fde68da196036feeb25b99d  # frozen: v1.11.2
  hooks:
  - id: mypy
    args: ["--scripts-are-modules"]
    additional_dependencies:
    - pytest
